### ISSUE TITLE
unable to create capsnet_function

### ISSUE THREAD

**Issue by vijaykumarnadal** [dfalbel/capsnet#1]
hi,when i try to run the demo.r script i get the following error

Error in create_capsnet(input_shape = c(28, 28, 1), n_class = 10L, num_routing = 3L) : 
  could not find function "create_capsnet"

can you help me  to fix the error

**Comment by dfalbel** [comment]
Hi!

Sorry the package is still a work in progress. The code in demo wasn't the intended API :(
I just exported the `create_capsnet` function and it should work now. You will need to re-install the package.

**Comment by vijaykumarnadal** [comment]
thank you
